const ACTION_TYPES = {
  REST_LOADING: "REST_LOADING",
  REST_ERROR: "REST_ERROR",
  REST_SUCCESS: "REST_SUCCESS",

  CART_LOADING: "CART_LOADING",
  CART_ERROR: "CART_ERROR",
  CART_SUCCESS: "CART_SUCCESS",
  ADD_TO_CART: "ADD_TO_CART",
  UPDATE_AMOUNT: "UPDATE_AMOUNT",
  DELETE_FROM_CART: "DELETE_FROM_CART",
};

export default ACTION_TYPES;
